sudo: false
language: node_js
node_js:
  - "7"
  
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run build
  - rm -rf node_modules/ngx-weui
  - npm i ./dist
  - npm run test-coverage

after_success:
  - ./node_modules/.bin/codecov
